name: main-pr-branch-guard.yml

on:
  pull_request:
    branches: [ main ]

jobs:
  release-branch-only:
    name: release-branch-only
    runs-on: ubuntu-latest
    steps:
      - name: Ensure PR source branch matches v*.*.*
        env:
          HEAD_REF: ${{ github.head_ref }}
          PATTERN: '^v[0-9]+\.[0-9]+\.[0-9]+$'
        shell: bash
        run: |
          set -Eeuo pipefail
          if [[ "${HEAD_REF}" =~ ${PATTERN} ]]; then
            echo "OK: head_ref=${HEAD_REF} matches release pattern."
          else
            msg="BLOCKED: Only branches like v1.2.3 can merge to main. Got: ${HEAD_REF}"
            echo "${msg}"
            echo "${msg}" >> "${GITHUB_STEP_SUMMARY}"
            exit 1
          fi
